server:
  port: 7001

logging.level.com.trasier.client.spring.noop: TRACE

trasier:
  client:
    accountId: ${YOUR_ACCOUNT_ID}
    spaceKey: ${YOUR_SPACE_KEY}
    clientId: ${YOUR_CLIENT_ID}
    clientSecret: ${YOUR_CLIENT_SECRET}
    systemName: payment